### ISSUE TITLE
Unable to Initialize Provider Plugin (Terraform v0.13)

### ISSUE THREAD

**Issue by mattroark** [platform9/terraform-provider-pf9#6]
I am unable to initialize the provider plugin on Terraform `v0.13.4` after moving the generated binary to `$HOME/.terraform.d/plugins` and running `terraform init`.

```
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/pf9...

Error: Failed to install provider

Error while installing hashicorp/pf9: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/pf9
```

**Comment by bharrisp9** [comment]
https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-13.html.markdown#in-house-providers
This worked for me

**Comment by mithilarun** [comment]
Closing this. The provider has been published to the terraform registry.
